# Generated by Django 3.2.8 on 2021-10-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=120, verbose_name='Name of Venue')),
                ('manager', models.CharField(max_length=50, verbose_name='Manager')),
                ('description', models.TextField(verbose_name='Event Description')),
            ],
        ),
    ]
