# Generated by Django 3.2.8 on 2021-10-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211022_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='manager',
            new_name='event_manager',
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events.MyClubUser'),
        ),
    ]
