# Generated by Django 3.2.8 on 2021-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(default=0, upload_to='pics', verbose_name='Venue Picture'),
            preserve_default=False,
        ),
    ]
