# Generated by Django 3.2.8 on 2021-11-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_venue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
    ]
